[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[template.environment]
  GITHUB_ACCESS_TOKEN = "Your GitHub access token for committing changes"
  GITHUB_REPO_OWNER = "GitHub repository owner"
  GITHUB_REPO_NAME = "GitHub repository name"